const A={miona:new URL('./assets/miona.jpg',import.meta.url).href,arin:new URL('./assets/arin.jpg',import.meta.url).href,elsia:new URL('./assets/elsia.jpg',import.meta.url).href};
const seed={intro:'สวัสดีค่ะ ยินดีต้อนรับเข้าสู่สวนเล็ก ๆ ของเรา ♡',introEn:'Hi! Welcome to our tiny apple garden. This is a cozy place for my OCs, their worlds, and little stories.',ownerNote:'เป็นมุมเล็ก ๆ ที่เก็บเรื่องราวของโอซีและ AU ที่รัก',profileImage:'',characters:[
{id:'miona',name:'มาดาระเมะ มิอง',en:'Madarame Mion',nickname:'น้องหัวเหลือง',fandom:'Tokyo Revengers · ด้อมโตมัน',age:'15 ขวบ · years old',color:'yellow',image:A.miona,tag:'sunny apple',bio:'เด็กสาวผมเหลืองผู้ชอบวันที่แดดอุ่น ๆ',detail:'มิอง เด็กสาวอายุ 15 ขวบจากด้อมโตมัน ผู้มีบรรยากาศสดใสเหมือนแสงแดดบนผลแอปเปิ้ล',quote:'ขอให้วันนี้มีแดดอุ่น ๆ และเรื่องดี ๆ นะ!',aus:[{name:'main timeline',text:'เรื่องราวหลักในโลกโตมันและชีวิตประจำวันของมิอง'}]},
{id:'arin',name:'คัง อาริน',en:'Kang Arin',nickname:'น้องหัวแดง',fandom:'Weak Hero · โรงเรียนสตรี',age:'school girl · นักเรียน',color:'red',image:A.arin,tag:'red apple',bio:'เด็กสาวหัวแดงจากโรงเรียนสตรี ผู้มีหัวใจกล้าหาญ',detail:'อารินดูนิ่งและมีระยะห่างเล็กน้อย แต่จริง ๆ แล้วใส่ใจกับคนรอบตัวมาก และพร้อมปกป้องสิ่งสำคัญ',quote:'ไม่เป็นไร ฉันจัดการเองได้',aus:[{name:'school days',text:'AU โรงเรียนสตรีที่อารินค่อย ๆ สร้างพื้นที่ปลอดภัยให้ตัวเอง'}]},
{id:'elsia',name:'เอลเซีย',en:'Elsia',nickname:'น้องหัวฟาง (???)',fandom:'That Time I Got Reincarnated as a Slime',age:'dark elf · ดาร์กเอลฟ์',color:'purple',image:A.elsia,tag:'wild apple',bio:'ดาร์กเอลฟ์ลึกลับที่ชอบซ่อนตัวในร่มไม้',detail:'เอลเซียคือดาร์กเอลฟ์ผู้มีเสน่ห์ลึกลับ ชอบร่มเงาของต้นไม้และจำรายละเอียดเล็ก ๆ ของทุกคนได้ดี',quote:'ในป่านี้…ไม่มีอะไรหลุดสายตาฉันหรอก',aus:[{name:'forest au',text:'โลกแฟนตาซีที่เอลเซียใช้ชีวิตอยู่ท่ามกลางต้นไม้เก่าแก่และเวทมนตร์'}]}],
gallery:[{image:A.miona,label:'mion in the kitchen',sub:'มิอง · sunny days',color:'yellow'},{image:A.arin,label:'arin, softly',sub:'อาริน · red mood',color:'red'},{image:A.elsia,label:'elsia under leaves',sub:'เอลเซีย · forest au',color:'purple'}]};
const S={content:structuredClone(seed),token:localStorage.getItem('apple-admin-token'),lang:'th'},$=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)],esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'})[c]);
function merge(x){const n={...S.content,...x};n.ownerNote=n.ownerNote||seed.ownerNote;n.profileImage=n.profileImage||'';n.characters=(Array.isArray(n.characters)?n.characters:seed.characters).map((c,i)=>({...seed.characters[i],...c,aus:Array.isArray(c.aus)?c.aus:[]}));n.gallery=Array.isArray(n.gallery)?n.gallery:structuredClone(seed.gallery);return n}
function profile(){const yes=!!S.content.profileImage;['#profileImage','#avatarImage'].forEach(s=>{const i=$(s);i.hidden=!yes;if(yes)i.src=S.content.profileImage});$('#portraitPlaceholder').hidden=yes;$('#avatarPlaceholder').hidden=yes}
function chars(){$('#characterGrid').innerHTML=S.content.characters.map((c,i)=>'<article class="character-card '+esc(c.color)+'" style="--delay:'+(i*80)+'ms"><div class="character-image-wrap"><img src="'+esc(c.image)+'" alt="'+esc(c.name)+'"><span class="character-sticker">'+(i===0?'☼':i===1?'♡':'✦')+'</span></div><div class="character-copy"><span class="character-tag">'+esc(c.tag)+'</span><h3>'+esc(c.name)+'</h3><p class="english-name">'+esc(c.en)+'</p><p class="character-meta">'+esc(c.nickname)+' · '+esc(c.age)+'</p><p>'+esc(c.bio)+'</p><div class="fandom-label">'+esc(c.fandom)+'</div><button class="small-link" data-detail="'+esc(c.id)+'">read full detail ↗</button></div></article>').join('')}
function gallery(){$('#galleryCount').textContent=String(S.content.gallery.length).padStart(2,'0')+' photos';$('#galleryGrid').innerHTML=S.content.gallery.map((g,i)=>'<figure class="gallery-item '+esc(g.color)+'" style="--rotation:'+(i%2?'2deg':'-2deg')+'"><div class="gallery-image"><img src="'+esc(g.image)+'" alt="'+esc(g.label)+'" loading="lazy"><span>♡</span></div><figcaption><b>'+esc(g.label)+'</b><small>'+esc(g.sub)+'</small></figcaption></figure>').join('')}
function render(){ $('[data-content="intro"]').textContent=S.content.intro;$('[data-content="introEn"]').textContent=S.content.introEn;$('[data-content="ownerNote"]').textContent=S.content.ownerNote;profile();chars();gallery()}
function page(p,hash=true){$$('.page').forEach(x=>x.classList.toggle('active',x.id==='page-'+p));$$('.nav-tab').forEach(x=>x.classList.toggle('active',x.dataset.page===p||(p==='character-detail'&&x.dataset.page==='characters')));if(hash)location.hash=p;scrollTo({top:0,behavior:'smooth'})}
function detail(id){const c=S.content.characters.find(x=>x.id===id);if(!c)return;const au=(c.aus||[]).map(a=>'<div class="au-card"><b>'+esc(a.name)+'</b><p>'+esc(a.text)+'</p></div>').join('');$('#detailContent').innerHTML='<div class="detail-hero '+esc(c.color)+'"><div class="detail-image"><img src="'+esc(c.image)+'" alt="'+esc(c.name)+'"></div><div class="detail-summary"><span class="character-tag">'+esc(c.tag)+'</span><h2>'+esc(c.name)+'</h2><p class="english-name">'+esc(c.en)+'</p><p class="character-meta">'+esc(c.nickname)+' · '+esc(c.age)+'</p><div class="fandom-label">'+esc(c.fandom)+'</div></div></div><article class="detail-paper"><p class="eyebrow">oc detail · เรื่องราวของโอซี</p><p class="detail-copy">'+esc(c.detail||c.bio)+'</p><div class="quote-box">“'+esc(c.quote||'')+'”</div><div class="au-heading"><span>✿</span><h3>AU garden · โลกที่กำลังเติบโต</h3><span>✿</span></div><div class="au-grid">'+(au||'<p class="empty-copy">ยังไม่มี AU detail</p>')+'</div></article>';page('character-detail',false)}
function modal(id,open){$('#'+id).hidden=!open;document.body.classList.toggle('modal-open',open||!!$('.modal-backdrop:not([hidden])'))}
function fill(){const c=S.content;$('#contentForm [name="intro"]').value=c.intro;$('#contentForm [name="introEn"]').value=c.introEn;$('#contentForm [name="ownerNote"]').value=c.ownerNote;$('#contentForm [name="profileImage"]').value=c.profileImage||'';$('#characterAdminList').innerHTML=c.characters.map(x=>'<fieldset class="admin-character" data-character-id="'+x.id+'"><legend>'+esc(x.name)+' · '+esc(x.en)+'</legend><div class="admin-two-col"><label>ไทย / name<input data-field="name" value="'+esc(x.name)+'"></label><label>English name<input data-field="en" value="'+esc(x.en)+'"></label></div><div class="admin-two-col"><label>nickname<input data-field="nickname" value="'+esc(x.nickname)+'"></label><label>age / status<input data-field="age" value="'+esc(x.age)+'"></label></div><label>fandom<input data-field="fandom" value="'+esc(x.fandom)+'"></label><label>image URL<input data-field="image" value="'+esc(x.image)+'"></label><div class="admin-two-col"><label>color<select data-field="color"><option value="yellow" '+(x.color==='yellow'?'selected':'')+'>soft yellow</option><option value="red" '+(x.color==='red'?'selected':'')+'>apple red</option><option value="purple" '+(x.color==='purple'?'selected':'')+'>berry purple</option></select></label><label>tag<input data-field="tag" value="'+esc(x.tag)+'"></label></div><label>short bio<textarea data-field="bio" rows="2">'+esc(x.bio)+'</textarea></label><label>full detail<textarea data-field="detail" rows="3">'+esc(x.detail||'')+'</textarea></label><label>quote<input data-field="quote" value="'+esc(x.quote||'')+'"></label><label>AU details<small class="field-note">one line: AU name | description</small><textarea data-field="aus" rows="3">'+esc((x.aus||[]).map(a=>a.name+' | '+a.text).join('\n'))+'</textarea></fieldset>').join('');$('#galleryAdminList').innerHTML=c.gallery.map((g,i)=>'<fieldset class="admin-gallery-item"><legend>photo '+(i+1)+'</legend><div class="admin-two-col"><label>image URL<input data-field="image" value="'+esc(g.image)+'"></label><label>caption<input data-field="label" value="'+esc(g.label)+'"></label></div><div class="admin-two-col"><label>sub-caption<input data-field="sub" value="'+esc(g.sub)+'"></label><label>color<select data-field="color"><option value="yellow" '+(g.color==='yellow'?'selected':'')+'>soft yellow</option><option value="red" '+(g.color==='red'?'selected':'')+'>apple red</option><option value="purple" '+(g.color==='purple'?'selected':'')+'>berry purple</option></select></label></div><button type="button" class="remove-gallery-button" data-remove-gallery="'+i+'">remove photo</button></fieldset>').join('')}
async function save(msg){localStorage.setItem('apple-content',JSON.stringify(S.content));render();try{const r=await fetch('/api/content',{method:'PATCH',headers:{'Content-Type':'application/json',Authorization:'Bearer '+S.token},body:JSON.stringify(S.content)});if(!r.ok)throw Error();$(msg).textContent='saved softly ♡ · บันทึกแล้ว'}catch{$(msg).textContent='saved on this device ♡ · บันทึกในเครื่องแล้ว'}}
$$('.nav-tab').forEach(b=>b.addEventListener('click',()=>page(b.dataset.page)));$$('[data-go]').forEach(b=>b.addEventListener('click',()=>page(b.dataset.go)));$('#characterGrid').addEventListener('click',e=>{const b=e.target.closest('[data-detail]');if(b)detail(b.dataset.detail)});$('#adminButton').addEventListener('click',()=>S.token?(fill(),modal('adminModal',true)):modal('loginModal',true));$$('[data-close]').forEach(b=>b.addEventListener('click',()=>modal(b.dataset.close,false)));$$('.modal-backdrop').forEach(b=>b.addEventListener('click',e=>{if(e.target===b)modal(b.id,false)}));
$('#loginForm').addEventListener('submit',async e=>{e.preventDefault();const m=$('#loginMessage');try{const r=await fetch('/api/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.fromEntries(new FormData(e.currentTarget)))});if(!r.ok)throw Error();S.token=(await r.json()).token;localStorage.setItem('apple-admin-token',S.token)}catch{m.textContent='ลองใหม่อีกครั้งนะ · please check your login';return}modal('loginModal',false);fill();modal('adminModal',true)});
$('#contentForm').addEventListener('submit',async e=>{e.preventDefault();S.content=merge({...S.content,...Object.fromEntries(new FormData(e.currentTarget))});await save('#saveMessage')});
$('#charactersAdminForm').addEventListener('submit',async e=>{e.preventDefault();S.content.characters=S.content.characters.map(c=>{const r=document.querySelector('[data-character-id="'+c.id+'"]'),v=f=>$('[data-field="'+f+'"]',r).value,aus=v('aus').split('\n').map(x=>x.trim()).filter(Boolean).map(x=>{const p=x.split('|');return{name:(p.shift()||'').trim(),text:p.join('|').trim()}});return{...c,name:v('name'),en:v('en'),nickname:v('nickname'),age:v('age'),fandom:v('fandom'),image:v('image'),color:v('color'),tag:v('tag'),bio:v('bio'),detail:v('detail'),quote:v('quote'),aus}});await save('#characterMessage');fill()});
$('#galleryForm').addEventListener('submit',async e=>{e.preventDefault();S.content.gallery.push(Object.fromEntries(new FormData(e.currentTarget)));await save('#galleryMessage');e.currentTarget.reset();fill()});
$('#galleryAdminForm').addEventListener('submit',async e=>{e.preventDefault();S.content.gallery=$$('.admin-gallery-item').map(r=>({image:$('[data-field="image"]',r).value,label:$('[data-field="label"]',r).value,sub:$('[data-field="sub"]',r).value,color:$('[data-field="color"]',r).value}));await save('#gallerySaveMessage');fill()});
$('#galleryAdminList').addEventListener('click',e=>{const b=e.target.closest('[data-remove-gallery]');if(b){S.content.gallery.splice(Number(b.dataset.removeGallery),1);fill()}});
$('#resetContent').addEventListener('click',async()=>{S.content=structuredClone(seed);await save('#saveMessage');fill()});$('#logoutButton').addEventListener('click',()=>{S.token=null;localStorage.removeItem('apple-admin-token');modal('adminModal',false)});$('#year').textContent=new Date().getFullYear();function tick(){$('#clock').textContent=new Intl.DateTimeFormat('en',{hour:'numeric',minute:'2-digit'}).format(new Date()).toLowerCase()}tick();setInterval(tick,30000);try{const x=JSON.parse(localStorage.getItem('apple-content'));if(x)S.content=merge(x)}catch{}const p=location.hash.slice(1);if(['about','characters','gallery'].includes(p))page(p,false);if(p.startsWith('character-'))page('characters',false);fetch('/api/content').then(r=>r.ok?r.json():null).then(x=>{if(x){S.content=merge(x);render()}}).catch(()=>{});render();
